# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3b33e96dadf50fbdf0406399b9e5d47963e6580d3574b4c2b0656be6832ba74e46a8bcca97e0a2e81e8f1cb456ac320112feecf4591f697c138a83211b9883b

test:
  secret_key_base: cca04ff023c9063e1a0b4fc8ddc1d44e365018a54e2e5a3b56f0e8509691797366d38b24339c53b3f3eca5708cd72ab837314071f8e7930e84c306498485a5b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
